In [2]:
import pandas as pd
pd.__version__

'1.3.4'

DataFrame

In [3]:
#创建DataFrame
data = [['Google',10],['Runoob',12],['Wiki',13]]   #定义二维数组
df = pd.DataFrame(data,columns=['Site','Age'])
print(df)

     Site  Age
0  Google   10
1  Runoob   12
2    Wiki   13

In [3]:
#使用字典创建
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20},{'a':12,'b':25,'c':10}]
df = pd.DataFrame(data)
print (df)

    a   b     c
0   1   2   NaN
1   5  10  20.0
2  12  25  10.0

In [4]:
#属性
/*
shape:获取维度
index:获取行索引
columns:获取列索引
head()：查看前几行内容 （默认5行）
tail()：查看后几行内容（默认5行）
*/

SyntaxError: invalid character '：' (U+FF1A) (Temp/ipykernel_36556/1134834183.py, line 6)

In [5]:
print(df.shape)
print(df.index)
print(df.columns)
print(df.head(2))
print(df.tail(2))

(3, 3)
RangeIndex(start=0, stop=3, step=1)
Index(['a', 'b', 'c'], dtype='object')
   a   b     c
0  1   2   NaN
1  5  10  20.0
    a   b     c
1   5  10  20.0
2  12  25  10.0

In [6]:
df

    a   b     c
0   1   2   NaN
1   5  10  20.0
2  12  25  10.0

In [7]:
#索引
#1.直接索引（先列后行，且只能使用标签值）
print(df['a'][2])
print(df['c'][0])

12
nan

In [8]:
#2.loc/iloc函数(loc使用标签索引，iloc使用数字索引，但顺序均为先行后列)
print(df.loc[[0,1],['a','c']])
print(df.iloc[[0,1],[0,2]])
print(df.loc[0,'c'])
print(df.iloc[0,2])
print(df.loc[2])       #返回的是Series格式
print(df.loc[[0,1,2],'a'])  #返回的是Series格式

   a     c
0  1   NaN
1  5  20.0
   a     c
0  1   NaN
1  5  20.0
nan
nan
a    12.0
b    25.0
c    10.0
Name: 2, dtype: float64
0     1
1     5
2    12
Name: a, dtype: int64

In [9]:
#获取特定行
print(df.loc[0])
print(df.loc[[0,2]])
print(type(df.loc[0]))

a    1.0
b    2.0
c    NaN
Name: 0, dtype: float64
    a   b     c
0   1   2   NaN
2  12  25  10.0
<class 'pandas.core.series.Series'>

In [10]:
#获取特定列
print(df['a'])
print(df[['a','c']])
print(df.b)

0     1
1     5
2    12
Name: a, dtype: int64
    a     c
0   1   NaN
1   5  20.0
2  12  10.0
0     2
1    10
2    25
Name: b, dtype: int64

In [11]:
#修改操作
df.loc[0,'c']=100;
print(df)

    a   b      c
0   1   2  100.0
1   5  10   20.0
2  12  25   10.0

In [12]:
df['c'][0]=10
print(df)

    a   b     c
0   1   2  10.0
1   5  10  20.0
2  12  25  10.0

C:\Users\Jason\AppData\Local\Temp/ipykernel_36556/1443625606.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['c'][0]=10

In [13]:
df.a[2]=100
print(df)

     a   b     c
0    1   2  10.0
1    5  10  20.0
2  100  25  10.0

C:\Users\Jason\AppData\Local\Temp/ipykernel_36556/3685501599.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.a[2]=100

In [17]:
print(df.loc[:,['a','c']])  #第一列和第三列
print(df.loc[:,'a':'c'])   #第一列到第三列

     a     c
0    1  10.0
1    5  20.0
2  100  10.0
     a   b     c
0    1   2  10.0
1    5  10  20.0
2  100  25  10.0

In [28]:
#单独选取某些行
#1.
print(df[0:3])
#2.
print(df[0:1])

     a   b     c
0    1   2  10.0
1    5  10  20.0
2  100  25  10.0
   a  b     c
0  1  2  10.0

#其他操作

In [36]:
#赋值
df['a']=100;
df

     a   b     c
0  100   2  10.0
1  100  10  20.0
2  100  25  10.0

In [37]:
df.a[0]=200
df

C:\Users\Jason\AppData\Local\Temp/ipykernel_36556/1147849200.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.a[0]=200

     a   b     c
0  200   2  10.0
1  100  10  20.0
2  100  25  10.0

In [40]:
df['c'][0]=200
df

C:\Users\Jason\AppData\Local\Temp/ipykernel_36556/2061620180.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['c'][0]=200

     a   b      c
0  200   2  200.0
1  100  10   20.0
2  100  25   10.0

In [45]:
#排序
df2=df.sort_values(by='b',ascending=False) #降序排序
print(df)
print(df2)
#排序后原df不变，返回排序后的副本

     a   b      c
0  200   2  200.0
1  100  10   20.0
2  100  25   10.0
     a   b      c
2  100  25   10.0
1  100  10   20.0
0  200   2  200.0

In [46]:
df3=df.sort_index(axis=0,ascending=False) #按行索引降序排序
print(df)
print(df3)

     a   b      c
0  200   2  200.0
1  100  10   20.0
2  100  25   10.0
     a   b      c
2  100  25   10.0
1  100  10   20.0
0  200   2  200.0

In [47]:
df4=df.sort_index(axis=1,ascending=False) #按行索引降序排序
print(df)
print(df4)

     a   b      c
0  200   2  200.0
1  100  10   20.0
2  100  25   10.0
       c   b    a
0  200.0   2  200
1   20.0  10  100
2   10.0  25  100

#算数逻辑运算